% data table: median RTs per participant (=lines) and condition (=columns,
% one column for each condition combination, e.g. jumpSize1 and
% stochasticity level 1)
data = table( ...
    [3 6 4 3]', ... % each cell has the values of all participants in that condition
    [4 6 4 2]', ...
    [5 7 5 2]', ...
    [4 5 3 3]', ...
    [8 9 8 7]', ...
    [12 13 12 11]', ...
    'VariableNames', ...
    {'jumpSize1stocha1','jumpSize1stocha2','jumpSize11stocha3',...
    'jumpSize2stocha1','jumpSize2stocha2','jumpSize2stocha3'}); % and more for more jump sizes

withinFactors = table(...
    categorical([1 1 1 2 2 2])',... % all levels of jumpSize
    categorical([1 2 3 1 2 3])',... % all levels of stochasticity
    'VariableNames',{'jumpSize','stochasticity'});

rm = fitrm(data, ... % we have to name all variables and say we'll predict them by the group factor "1" (because we have no group factor)
    'jumpSize1stocha1,jumpSize1stocha2,jumpSize1stocha3,jumpSize2stocha1,jumpSize2stocha2,jumpSize2stocha3~1',... 
    'WithinDesign', withinFactors);

ranova(rm, 'WithinModel', 'a*b-1')